import type { Metadata } from "next";
import { Space_Grotesk, IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

// Display face: distinctive, confident, tight tracking on big moments.
const display = Space_Grotesk({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

// Body / UI face.
const body = IBM_Plex_Sans({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

// Numerals, labels, point numbers.
const mono = IBM_Plex_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["500", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://thebackgammonbaddie.com"),
  title: "The Backgammon Baddie: Play backgammon free",
  description:
    "Play backgammon free against The Baddie, a cheeky but honest computer opponent. One click, no signup, and your game saves right in your browser.",
  applicationName: "The Backgammon Baddie",
  openGraph: {
    type: "website",
    siteName: "The Backgammon Baddie",
    title: "The Backgammon Baddie",
    description:
      "One click into a real backgammon game against The Baddie. No signup, no app. Beat it if you can.",
    url: "https://thebackgammonbaddie.com",
    // og:image is generated by app/opengraph-image.tsx (Next file convention).
  },
  twitter: {
    card: "summary_large_image",
    title: "The Backgammon Baddie",
    description: "One click into a real backgammon game against The Baddie. No signup, no app.",
    // twitter:image is generated by app/twitter-image.tsx.
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${display.variable} ${body.variable} ${mono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
